const modalVitoria = document.createElement("section");
const section      = document.createElement("section");
const btnSair      = document.createElement("button");
const span         = document.createElement("span");
const body         = document.querySelector("body");
const div          = document.createElement("div");
const board        = document.createElement("div");
const torre1       = document.createElement("div");
const torre2       = document.createElement("div");
const torre3       = document.createElement("div");
const h1           = document.createElement("h1");
const h2           = document.createElement("h2");
const h3           = document.createElement("h3");
torre1.className  = "torre1";
torre2.className  = "torre2";
torre3.className  = "torre3";
board.className   = "Tabuleiro";
btnSair.className = "btn_sair";
h2.className      = "h2_win";
modalVitoria.setAttribute("id", "modal_vitoria");
h1.innerHTML      = "Torre de Hanói";
h2.innerHTML      = "Parabéns! Você ganhou!";
h3.innerHTML      = "Selecione a quantidade de discos";
span.innerHTML    = "Maximo de 9 discos e minimo de 3 discos";
btnSair.innerHTML = "X";
body.appendChild(section);
board.appendChild(torre1);
board.appendChild(torre2);
board.appendChild(torre3);
section.appendChild(h1);
section.appendChild(h3);
section.appendChild(span);
section.appendChild(div);
modalVitoria.appendChild(btnSair);
modalVitoria.appendChild(h2);